export const eventDetail = {
  getGlobalDocument: {
    data: {
      siteUrl: "pl-summit-22.vercel.app/",
      favicon:
        "https://res.cloudinary.com/protocolai/image/upload/v1665806845/pl-summit-22/pl-summit-favicon_k9dmro.png",
      gtmId: "",
      desktopWidth: "1440",
      backgroundColor: "white",
      redirects: null,
      colors: {
        primary: "#346DEE",
        accent1: "#092153",
        accent2: "#6DD6BE",
        accent3: "#54ACC8",
        accent4: "#FAC546",
        white: "#FFFFFF",
        grayLight: "#E8E8EF",
        gray: "#B0B0BF",
        grayDark: "#7B7A80",
        black: "#000000",
      },
      fonts: {
        font1: "Aileron",
        font2: "Source Code Pro:wght@400;700",
        font3: "Arial",
        font4: "Arial",
      },
      sizeLeading: {
        textXs: "14/12",
        textSm: "14/24",
        textMd: "16/23",
        textLg: "18/24",
        textXl: "24/32",
        text2xl: "34/42",
        text3xl: "28/40",
        text4xl: "32/44",
        text5xl: "39/48",
        text6xl: "48/48",
        text7xl: "72/84",
        text8xl: "96/120",
      },
      buttons: {
        primaryFill: "bg-primary opacity-100",
        primaryTypography: "text-white font-2 text-base mb-0 font-bold",
        primaryBorder: "border-accent3 border-r-0",
        primaryPadding: "pt-3 pb-3 pr-6 pl-6",
        primaryRounded: "rounded",
        secondaryFill: " opacity-100",
        secondaryTypography: "text-white undefined text-base undefined font-bold",
        secondaryBorder: "border-primary border-2",
        secondaryPadding: "pt-3 pb-3 pr-10 pl-10",
        secondaryRounded: "rounded-md",
        minorFill: " opacity-100",
        minorTypography: "text-white undefined text-base undefined font-bold",
        minorBorder: "border-white border-0",
        minorPadding: "pt-2 pb-2 pr-6 pl-6",
        minorRounded: "rounded-none",
      },
      logo: {
        logoType: "Microgen",
        logoTypeStyle: "text-white undefined text-base undefined font-bold",
        image: "https://res.cloudinary.com/protocolai/image/upload/v1665672995/pl-summit-22/protocol-pieces_azpkce.svg",
        imageWidth: "48",
        imageHeight: "37",
        imageMargin: "24",
      },
      nav: {
        navItems: [
          {
            link: "https://www.youtube.com/playlist?list=PLhuBigpl7lquMYyWetD-pjok5e-5Tv-MJ",
            label: "Watch the Recordings",
            subNavItems: null,
          },
        ],
        navAlignment: "text-right",
        navTypeStyle: "text-white font-1 text-base mb-0 ",
        navBackgroundColor: "bg-primary opacity-100",
        padding: "pt-4 pb-4 pr-20 pl-20 sm:pt-5 sm:pb-5 sm:pr-5 sm:pl-5",
      },
      blocks: null,
    },
  },
  getPagesDocument: {
    data: {
      blocks: [
        {
          __typename: "PagesBlocksFeature",
          style: {
            __typename: "PagesBlocksFeatureStyle",
            alignment: "flex-col items-center items-start-vertical gap-8",
            padding: "pt-32 pb-20 pr-20 pl-20 sm:pt-20 sm:pb-5 sm:pr-5 sm:pl-5",
            featureImage: "wpx-500 hpx- mr-auto",
            featureContent: "w-2/3 min-h-0 text-left",
            typographyTitle: null,
            labelStyles: "text-accent2 font-2 text-lg mb-1.5 font-bold",
            headlineStyles: "text-white font-1 text-5xl mb-7 ",
            subheadStyles: "text-gray font-1 text-xl mb-7 font-bold",
            textStyles: "text-white font-1 text-xl mb-11 ",
            contentOrder: "labelHeadingsContent",
          },
          background: {
            __typename: "PagesBlocksFeatureBackground",
            fillStyles: "bg-accent1 opacity-100",
            src: null,
            position: null,
            ornaments: [
              {
                __typename: "PagesBlocksFeatureBackgroundOrnaments",
                src: "https://res.cloudinary.com/protocolai/image/upload/v1665672982/pl-summit-22/hex-ornament_rtnce3.svg",
                alignment: "top",
                width: null,
                height: "660",
                xOffset: "650",
                yOffset: "70",
              },
            ],
          },
          image: {
            __typename: "PagesBlocksFeatureImage",
            src: "https://res.cloudinary.com/protocolai/image/upload/v1665672990/pl-summit-22/pl-summit-logo_pvrz3m.svg",
            alt: "Illustration of space shuttles",
          },
          rule: null,
          label: "October 24, 2022",
          headline: "PL Summit & Labweek22 Opening Party",
          subhead: "",
          body: `<p>The Protocol Labs Network is getting together for our first ever decentralized conference! Join us as we drive breakthroughs in computing to push humanity forward.`,
          buttons: [
            {
              __typename: "PagesBlocksFeatureButtons",
              label: "Watch the Recordings",
              link: "https://www.youtube.com/playlist?list=PLhuBigpl7lquMYyWetD-pjok5e-5Tv-MJ",
              type: "secondary",
            },
          ],
          rule2: null,
          navigationLabel: null,
        },
        {
          __typename: "PagesBlocksTailwindCards",
          tailwind: {
            __typename: "PagesBlocksTailwindCardsTailwind",
            section: "",
            wrap: "max-w-site-full mx-auto p-20 sm:p-5",
            imageWrap: "",
            image: "",
            contentWrap: "",
            content: "",
            label: "",
            headline: "",
            subhead: "",
            text: "",
            buttons: "",
            button: "",
            rule: null,
            cardWrap: null,
            card: "relative flex gap-8 items-center mb-8 sm:flex-col sm:mt-12",
            cardImageWrap: "w-5/12 sm:w-full sm:h-60",
            cardImage: "rounded-lg h-full w-full sm:object-cover",
            cardContentWrap: "w-7/12 sm:w-full",
            cardContent: "text-white",
            cardLabel:
              "absolute z-20 px-8 left-0 top-1/2 transform -translate-y-1/2 w-5/12 text-center font-1 font-bold text-xl text-accent1 sm:w-full sm:top-28",
            cardHeadline: "text-white text-4xl font-1 font-bold mb-3",
            cardSubhead: "text-accent2 text-base font-bold font-2 mb-6",
            cardText: "text-white text-base",
            cardButtons: null,
            cardButton: null,
          },
          image: null,
          background: {
            __typename: "PagesBlocksTailwindCardsBackground",
            fillStyles: "bg-accent1 opacity-100",
            src: null,
            position: null,
            ornaments: null,
          },
          rule: null,
          label: "",
          headline: "",
          subhead: "",
          body: "",
          buttons: null,
          items: [
            {
              __typename: "PagesBlocksTailwindCardsItems",
              image: {
                __typename: "PagesBlocksTailwindCardsItemsImage",
                src: "https://res.cloudinary.com/protocolai/image/upload/v1665676294/pl-summit-22/event-pl-summit_nmmypj.jpg",
                alt: null,
              },
              label: "PL Summit at Convento de Beato",
              headline: "PL Summit",
              subhead: "October 24, 11am - 3pm",
              text: `<p>The Protocol Labs Network will meet at Convento do Beato to hear Juan Benet's vision for the future of the network, learn more about the progress and impact being made by network teams, and prepare for a fun-filled week of learning, collaboration, and connection.</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksTailwindCardsItems",
              image: {
                __typename: "PagesBlocksTailwindCardsItemsImage",
                src: "https://res.cloudinary.com/protocolai/image/upload/v1665676289/pl-summit-22/event-opening-party_o9s5zi.jpg",
                alt: null,
              },
              label: "Opening Party at Estufa Fria",
              headline: "Opening Party",
              subhead: "October 24, 7pm - 11pm",
              text: `<p>In the evening, join the Protocol Labs Network at the beautiful Estufa Fria for the Lab Week opening party. We'll have cocktails, light bites, and music to kick the week off in style.</p>`,
              link: null,
              buttonLabel: null,
            },
          ],
          rule2: null,
          navigationLabel: "Agenda",
        },
        {
          __typename: "PagesBlocksTailwindCards",
          tailwind: {
            __typename: "PagesBlocksTailwindCardsTailwind",
            section: "",
            wrap: "max-w-site-full mx-auto px-20 sm:px-5",
            imageWrap: "",
            image: "",
            contentWrap: "max-w-site-1/2 mx-auto",
            content: "",
            label: "",
            headline: "text-white text-6xl font-1 font-bold text-center mb-10 sm:text-4xl",
            subhead: "",
            text: "",
            buttons: "",
            button: "",
            rule: null,
            cardWrap: "max-w-site-1/2 mx-auto text-center pb-6",
            card: "mb-10",
            cardImageWrap: null,
            cardImage: null,
            cardContentWrap: null,
            cardContent: "",
            cardLabel: null,
            cardHeadline: "font-2 text-accent2 font-bold text-xl",
            cardSubhead: null,
            cardText: "text-white text-lg font-1",
            cardButtons: null,
            cardButton: null,
          },
          image: null,
          background: {
            __typename: "PagesBlocksTailwindCardsBackground",
            fillStyles: "bg-accent1 opacity-100",
            src: null,
            position: null,
            ornaments: null,
          },
          rule: null,
          label: "",
          headline: "Venues",
          subhead: "",
          body: "",
          buttons: null,
          items: [
            {
              __typename: "PagesBlocksTailwindCardsItems",
              image: null,
              label: null,
              headline: "Convento do Beato",
              subhead: "",
              text: `<p>Alameda do Beato 40, 1950-042 Lisboa, Portugal</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksTailwindCardsItems",
              image: null,
              label: null,
              headline: "Estufa Fria",
              subhead: "",
              text: `<p>Parque Eduardo VII, 1070-051 Lisboa, Portugal</p>`,
              link: null,
              buttonLabel: null,
            },
          ],
          rule2: null,
          navigationLabel: "Location",
        },
        {
          __typename: "PagesBlocksTailwindFeature",
          tailwind: {
            __typename: "PagesBlocksTailwindFeatureTailwind",
            section: "",
            wrap: "max-w-site-full px-20 mx-auto pb-28 sm:px-5 sm:pb-10",
            imageWrap: "",
            image: "",
            contentWrap: "",
            content: "",
            label: "",
            headline: "",
            subhead: "",
            text: "",
            buttons: "",
            button: null,
          },
          image: {
            __typename: "PagesBlocksTailwindFeatureImage",
            src: "https://res.cloudinary.com/protocolai/image/upload/v1665672987/pl-summit-22/map_dk6w44.png",
            alt: null,
          },
          background: {
            __typename: "PagesBlocksTailwindFeatureBackground",
            fillStyles: "bg-accent1 opacity-100",
            src: "",
            position: null,
            ornaments: null,
          },
          rule: null,
          label: "",
          headline: "",
          subhead: "",
          body: "",
          buttons: null,
          rule2: null,
          navigationLabel: null,
        },
        {
          __typename: "PagesBlocksAccordian",
          style: {
            __typename: "PagesBlocksAccordianStyle",
            textAlignment: "text-left",
            padding: "pt-0 pb-20 pr-20 pl-20 sm:pt-0 sm:pb-10 sm:pr-5 sm:pl-5",
            contentWidth: "w-full",
            typographyTitle: null,
            labelStyles: "text-white font-1 text-sm mb-0 ",
            headlineStyles:
              "text-white font-1 text-6xl mb-10 font-bold sm:text-white sm:font-1 sm:text-4xl sm:mb-5 sm:font-bold",
            subheadStyles: "text-white font-1 text-3xl mb-0 ",
            textStyles: "text-white font-1 undefined mb-0 ",
            contentOrder: "labelHeadingsContent",
          },
          cardStyle: {
            __typename: "PagesBlocksAccordianCardStyle",
            fillStyles: " opacity-100",
            padding: "pt-2.5 pb-2.5 pr-2.5 pl-2.5",
            borderStyles: "border-primary border-1",
            imageStyles: " undefined undefined undefined",
            typographyTitle: null,
            labelStyles: "text-white undefined text-lg mb-0  sm:text-white sm:font-1 sm:text-base sm:mb-0 ",
            headlineStyles: "text-white undefined text-lg mb-0  sm:text-white sm:font-1 sm:text-base sm:mb-0 ",
            subheadStyles: "text-white undefined text-lg mb-0  sm:text-white sm:font-1 sm:text-base sm:mb-0 ",
            textStyles: "text-white undefined text-lg mb-0  sm:text-white sm:font-1 sm:text-base sm:mb-0 ",
            buttonTitle: null,
            buttonType: "primary",
          },
          background: {
            __typename: "PagesBlocksAccordianBackground",
            fillStyles: "bg-accent1 opacity-100",
            src: null,
            position: null,
            ornaments: null,
          },
          label: "",
          headline: "FAQs",
          subhead: "",
          body:"",
          buttons: null,
          items: [
            {
              __typename: "PagesBlocksAccordianItems",
              label: "",
              headline: "What is PL Summit? Who is it for?",
              subhead: "",
              text: `<p>PL Summit is open to anyone who wants to hear Juan Benet's vision for the future of the network, learn more about the progress and impact being made by network teams, and prepare for a fun-filled week of learning, collaboration, and connection.</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksAccordianItems",
              label: null,
              headline: "How do I register? What does the ticket include?",
              subhead: "",
              text: `<p>Please register using the following <a href="https://lu.ma/plsummit22">link</a>. The ticket includes entry to PL Summit at Convento do Beato and the Opening Party at Estufa Fria.</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksAccordianItems",
              label: null,
              headline: "Will there be transportation from the PL Summit to the Opening Party?",
              subhead: "",
              text: `<p>Yes! We will have shuttles running from Convento do Beato to Estufa Fria for all badge holders.</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksAccordianItems",
              label: null,
              headline: "What's the COVID-19 policy?",
              subhead: null,
              text: `<p>PL Summit will follow COVID-19 protocols set for Lab Week. Please review the policy <a href="https://coda.io/@stellarevents/labweek22/covid-19-policy-21">here</a>.</p>`,
              link: null,
              buttonLabel: null,
            },
            {
              __typename: "PagesBlocksAccordianItems",
              label: null,
              headline: "How do I reach the organizers?",
              subhead: null,
              text: `<p>Please reach out to <a href="mailto:labweek22@protocol.ai">labweek22@protocol.ai</a> with any questions or suggestions!</p>`,
              link: null,
              buttonLabel: null,
            },
          ],
          navigationLabel: "FAQs",
        },
        {
          __typename: "PagesBlocksTailwindCards",
          tailwind: {
            __typename: "PagesBlocksTailwindCardsTailwind",
            section: "",
            wrap: "max-w-site-full mx-auto px-20 py-10 sm:px-5",
            imageWrap: "",
            image: "",
            contentWrap: "",
            content: "",
            label: "",
            headline: "",
            subhead: "",
            text: "",
            buttons: "",
            button: "",
            rule: null,
            cardWrap: "flex justify-end gap-16",
            card: "",
            cardImageWrap: null,
            cardImage: null,
            cardContentWrap: "",
            cardContent: "",
            cardLabel: null,
            cardHeadline: "text-xs font-2 font-bold mb-4",
            cardSubhead: null,
            cardText: "text-xs font-1",
            cardButtons: null,
            cardButton: null,
          },
          image: null,
          background: {
            __typename: "PagesBlocksTailwindCardsBackground",
            fillStyles: "from-accent2 to-accent3 bg-gradient-to-tr opacity-100",
            src: null,
            position: null,
            ornaments: null,
          },
          rule: null,
          label: "",
          headline: "",
          subhead: "",
          body: "",
          buttons: null,
          items: [
            {
              __typename: "PagesBlocksTailwindCardsItems",
              image: null,
              label: null,
              headline: "Links",
              subhead: "",
              text:`<p><a href="https://protocol.ai">Protocol Labs</a></p>          <p><a href="#">Event Github</a></p>`,
              link: null,
              buttonLabel: null,
            },
          ],
          rule2: null,
          navigationLabel: null,
        },
      ],
      meta: {
        __typename: "PagesMeta",
        pageTitle: "PL Summit",
        pageDescription:
          "The Protocol Labs Network is getting together for our first ever decentralized conference! Join us as we drive breakthroughs in computing to push humanity forward.",
        siteImageSrc: null,
      },
    },
  },
};
